spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
              user-name-attribute: sub

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: secretKeyForJWT12345
  expirationMs: 86400000

logging:
    level:
      org.springframework.security.oauth2: DEBUG
      com.smartloansuite.user_service: DEBUG
